# Do not change version. This is the version of aws buildspec, not the version of your buldspec file.
version: 0.2
phases:
  install:
    commands:
      - echo Installing Node 12...
      - curl -fsSL https://rpm.nodesource.com/setup_14.x | bash -
      - sudo yum install nodejs
      - echo Installing Yarn...
      - curl --silent --location https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
      - sudo rpm --import https://dl.yarnpkg.com/rpm/pubkey.gpg
      - sudo yum install yarn
  pre_build:
    commands:
      - echo Installing dependencies...
      - yarn
  build:
    commands:
      - echo Build started on `date`
      - echo Building...
      - yarn build
  post_build:
    commands:
      - echo Build completed on `date`
# Include only the files required for your application to run.
artifacts:
  files:
    - public/**/*
    - src/**/*
    - package.json
    - appspec.yml
    - scripts/**/*
    - server.js