/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "xxx",
    "aws_appsync_graphqlEndpoint": "xxx",
    "aws_appsync_region": "xxx",
    "aws_appsync_authenticationType": "xxx",
    "aws_appsync_apiKey": "xxx"
};


export default awsmobile;
